### ISSUE TITLE
[GAME BUG] Mortal Kombat Trilogy Bell tower pit 

### ISSUE THREAD

**Issue by ELGUAPO69** [AppCakeLtd/fenrir-bug-reports#5]
**Game Name**
Mortal Kombat Trilogy 

**Game Region**
USA

**Game Source**
- [x] Redump (cue/bin)
- [x] Trurip (ccd/img)
- [ ] Other (iso)
- [ ] Other (cue/bin)
- [ ] Other (ccd/img)

**Describe the bug**
Game plays fine until you get to the bell tower.. when they uppercut you with there fatality and you start to fall down.. game crackles and freezes.. have to reboot console all over again.. tried it even with the European version too! It did it again now on another stage when the fighter was gonna do a brutality just froze!

**Console Revision**
If you don't know the revision of your console, please leave blank
- [ ] VA0
- [ ] VA0.5
- [ ] VA0.8
- [ ] VA1

**Console Region**
- [ ] PAL
- [ ] NTSC-U
- [x] NTSC-J
- [ ] Other

**Firmware and Loader Version**
To check your firmware and loader version, go to the Options in the Loader app (Start button). The text next to "FW" is your board's firmware, and the text next to "V" is the Loader version.
- Firmware Version: 6cdf9cc3
- Loader Version: 2afdf05

**Cartridge Attached**
(Please select more than one if it applies)
- [ ] None
- [x] Action Replay 3 in 1
- [ ] Pseudo Saturn Kai / Kai Lite - Red Cartridge all in one
- [ ] Pseudo Saturn Kai - Custom Made
- [ ] Original Save Cartridge
- [ ] Third party Save Cartridge
- [ ] Original 1MB RAM Expansion
- [ ] Original 4MB RAM Expansion
- [ ] MPEG Card

**To Reproduce**
1. Launch Game with (A|B|C)
2. Do X in game
3. This happens

**Flex Cable Attached**
- [x] Original Flex Cable
- [ ] Replacement Flex Cable provided by 8BitMods
- [ ] Replacement Flex Cable Sourced by myself (please state where from and part number)

**Expected behavior**
No freezing on Fatality

**Comment by ELGUAPO69** [comment]
![20200622_211821](https://user-images.githubusercontent.com/67299070/85353553-1c57cc00-b4ce-11ea-8a8b-cffc1c57efd2.jpg)

**Comment by ELGUAPO69** [comment]
![20200622_211843](https://user-images.githubusercontent.com/67299070/85353576-2ed20580-b4ce-11ea-9320-b8a818ef6bc6.jpg)

**Comment by ELGUAPO69** [comment]
Arquivista.exe Copy works marvelous!!

**Comment by ThanosSiopoudis** [comment]
Let's keep this open please, as it's still an issue with Redump

**Comment by craigsblackie** [comment]
I too experienced a similar crash when receiving a brutality.

**Comment by ThanosSiopoudis** [comment]
Fixed in version `da719d1b`
