### ISSUE TITLE
Shinobi Legions (US) [GAME BUG]

### ISSUE THREAD

**Issue by jpipes** [AppCakeLtd/fenrir-bug-reports#6]
*IMPORTANT*
Please only use this page to report compatibility issues with Fenrir. If you are looking for generic support, please contact hello@8bitmods.com

**Game Name**
Shinobi Legions (US)
**Game Region**
The region of the game

**Game Source**
- [X] Redump (cue/bin)
- [ ] Trurip (ccd/img)
- [ ] Other (iso)
- [ ] Other (cue/bin)
- [ ] Other (ccd/img)

**Describe the bug**
A clear and concise description of what happens when you attempt to launch, or when you play the game.

**Console Revision**
If you don't know the revision of your console, please leave blank
- [ ] VA0
- [ ] VA0.5
- [ ] VA0.8
- [ ] VA1
The region select screen within the loader shows my BIOS is US_BTR_1.000U941115, I'm guessing this is a VA1 board.

**Console Region**
- [ ] PAL
- [X] NTSC-U
- [ ] NTSC-J
- [ ] Other

**Firmware and Loader Version**
To check your firmware and loader version, go to the Options in the Loader app (Start button). The text next to "FW" is your board's firmware, and the text next to "V" is the Loader version.
- Firmware Version: 6cdf9cc3
- Loader Version: 2afdf05

**Cartridge Attached**
(Please select more than one if it applies)
- [X] None
- [X] Action Replay 3 in 1
- [ ] Pseudo Saturn Kai / Kai Lite - Red Cartridge all in one
- [ ] Pseudo Saturn Kai - Custom Made
- [ ] Original Save Cartridge
- [ ] Third party Save Cartridge
- [ ] Original 1MB RAM Expansion
- [ ] Original 4MB RAM Expansion
- [ ] MPEG Card

**To Reproduce**
1. Launch Game with (A)
2. Start game.
3. Game freezes and music starts repeating at the stage 1 start screen.

1. Launch Game with (B)
2. Start game.
3. Game freezes on black screen.

1. Launch Game with (C) (Action Replay 4m Plus)
2. Start Game and play through the first level.
3. After the first boss is defeated and the score screen comes up, the game freezes at a black screen.

**Flex Cable Attached**
- [x] Original Flex Cable
- [X] Replacement Flex Cable provided by 8BitMods
- [ ] Replacement Flex Cable Sourced by myself (please state where from and part number)

**Expected behavior**
Game should continue loading

**Screenshots / Photos**
If applicable, add screenshots or photos to help explain your problem.

**Additional context**

**Comment by ThanosSiopoudis** [comment]
Fixed in version `da719d1b`
